name: dmgt
channels:
  - pytorch
dependencies:
  - pip
  - python=3.9
  - numpy
  - numpy-base
  - matplotlib
  - matplotlib-base
  - pandas
  - seaborn
  - tqdm
  - pytorch
  - torchvision
  - scikit-learn
  - sympy
  - line_profiler
